services:
  - type: web
    name: tiktok-scraper
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile  # <-- point to your Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
