services:
  - type: web
    name: tiktok-scraper
    runtime: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3-pip ffmpeg
      pip install yt-dlp
      npm install
      npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
